### PR TITLE
Use Comparator methods introduced in Java 8.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Use the `Comparator` factory methods introduced in Java 8.
* Clean up some unused methods.

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
@foobnix How can this be tested on Windows? I couldn't get the build scripts to work.

**Comment by foobnix** [comment]
Can't apply because the code does not work on old devices, for example

`res.sort(Comparator.comparing(FileMeta::getDate, Comparator.nullsLast(Comparator.naturalOrder())));`

require API 24

Librera F-Droid should run on Android 14 or at least on Android 19

**Comment by Isira-Seneviratne** [comment]
> Can't apply because the code does not work on old devices, for example
> 
> `res.sort(Comparator.comparing(FileMeta::getDate, Comparator.nullsLast(Comparator.naturalOrder())));`
> 
> require API 24
> 
> Librera F-Droid should run on Android 14 or at least on Android 19



> Can't apply because the code does not work on old devices, for example
> 
> `res.sort(Comparator.comparing(FileMeta::getDate, Comparator.nullsLast(Comparator.naturalOrder())));`
> 
> require API 24
> 
> Librera F-Droid should run on Android 14 or at least on Android 19

Core library desugaring [backports](https://developer.android.com/studio/write/java8-support-table) the APIs so that they are available on older Android versions.

**Comment by foobnix** [comment]
Thanks, I will add java8 support but can't migrate all changes - too many changes.
I will add it part by part manually - need to test and verify.

**Pull request closed without merging**
