### PR TITLE
Updated ga.xml

### PR DESCRIPTION
**Pull request by seananocoistin**
An updated Irish translation of the file.

### CODE REVIEW

**Comment by foobnix** [comment]
Please create folder [values-ga] with file strings.xml and dond modify other files

**Comment by seananocoistin** [comment]
Hi Ivan, I translated about half of the file yesterday or the day before. I do not see them in Github. Did you receive them? Seanán From: Ivan IvanenkoSent: Dé Sathairn 23 Bealtaine 2020 19:27To: foobnix/LibreraReaderCc: Seanán Ó Coistín; AuthorSubject: Re: [foobnix/LibreraReader] Updated ga.xml (#599) Please create folder [values-ga] with file strings.xml and dond modify other files—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by foobnix** [comment]
Yes, I see, I will prepare new build and notify yoy

**Comment by seananocoistin** [comment]
I was hoping to continue with the Irish translation and upload it but I could not find it.  I could just download it and translate it on my desktop and then upload once it is fully translated. Regards,Seanán From: Ivan IvanenkoSent: Dé Sathairn 23 Bealtaine 2020 19:38To: foobnix/LibreraReaderCc: Seanán Ó Coistín; AuthorSubject: Re: [foobnix/LibreraReader] Updated ga.xml (#599) Yes, I see, I will prepare new build and notify yoy—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by foobnix** [comment]
You can find it in you repository
https://github.com/seananocoistin/LibreraReader/blob/patch-4/app/src/main/res/values/strings.xml

**Comment by foobnix** [comment]
I have added Irish stub translated with Google Translate, please edit it 
https://github.com/foobnix/LibreraReader/blob/master/app/src/main/res/values-ga/strings.xml
you can also try beta.librera.mobi with this language

**Pull request closed without merging**
