### PR TITLE
A separate text string

### PR DESCRIPTION
**Pull request by Valdnet**
A separate text string for the screen settings and translation into Polish.

### CODE REVIEW

**Comment by foobnix** [comment]
Please do NOT modify Java code (like urn getString(R.string.normal); it will break all other languages

**Comment by Valdnet** [comment]
> Please do NOT modify Java code

I see. Please fix the problem with the text string that is common to the "Screen" and "Font Size" settings.

In other languages, including Polish, the "Normal" setting for "Screen" and "Font size" sounds different.
Currently I will add a PR with a revised Polish translation.

>  it will break all other languages

Translators can always add a translation. This is also done when adding new text strings.

**Comment by foobnix** [comment]
>Translators can always add a translation. This is also done when adding new text strings.
I agree with you if you can add a new text string for all other 20 languages, android crashes if there is no string_id in other languages.

Please make one new pull  request only with text corrections but without adding/modifying string_id
If you want to add a new string_id it should be a separate request and require some of my efforts.

**Comment by Valdnet** [comment]
Done 😉.

**Pull request closed without merging**
